controllers:
    resource:
        path: ../src/Infrastructure/Api/Http/Controller/
        namespace: Jerowork\ExampleApplicationGraphqlAttributeSchema\Infrastructure\Api\Http\Controller
    type: attribute
